version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "scala"

[[analyzers]]
name = "terraform"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "cxx"